---

- include_vars: "../vars/main.yml"

- name: Create game file directory for Killing Floor.
  file: path={{ steamcmd_gamefile_dir }}/killing_floor state=directory mode=0755 group=steam owner=steam

- name: Create game script for Killing Floor.
  template: src="../game_scripts/killing_floor.j2" dest={{ steamcmd_gamefile_dir }}/killing_floor owner=steam group=steam mode=0644
