---

- include_vars: "../vars/main.yml"

- name: Install packages for Debian based distros.
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
  - lib32gcc1
  become: yes
  become_user: root
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add user steam that steamcmd will run under.
  user: name=steam comment="Valve Steamcmd User" shell=/bin/bash createhome=yes
  become: yes
  become_user: root

- name: Create directory for SteamCMD.
  file: path=/home/steam state=directory mode=0755

- name: Download steamcmd.
  get_url: url={{ steamcmd_download_url }} dest=/home/steam/steamcmd_linux.tar.gz
  become: yes
  become_user: root

- name: Save path for steamcmd download.
  stat: path=/home/steam/steamcmd_linux
  register: steam_dir

- name: Uncompress steamcmd download.
  unarchive: src=/home/steam/steamcmd_linux.tar.gz dest=/home/steam copy=no group=steam owner=steam
  when: steam_dir.stat.exists == False
  become: yes
  become_user: root

- name: Create game file directory ( Default /mnt/steamcmd ).
  file: path={{ steamcmd_gamefile_dir }} state=directory mode=0755 group=steam owner=steam

# Build Killing Floor server.
- include: tasks/killing_floor.yml
